version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Pass123
    ports:
      - "1433:1433"
    networks:
      - app-net
    restart: unless-stopped

  backend:
    build:
      context: ./ProductPortalAPI
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=OvoJeSuperTajniKljucZaJWTToken123!
      - ConnectionStrings__DefaultConnection=Server=db;Database=ProductPortalDb;User Id=sa;Password=YourStrong!Pass123
    depends_on:
      - db
    networks:
      - app-net
    command: >
      sh -c "sleep 20 && dotnet ProductPortalAPI.dll"

  frontend:
    build:
      context: ./product-portal-frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
